SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(V.REVIEW_SCORE), 2) as SCORE
from REST_INFO I
inner join REST_REVIEW V on I.REST_ID = V.REST_ID
where I.ADDRESS like '서울%'
group by I.REST_ID
order by SCORE desc, I.FAVORITES desc;