select O.PRODUCT_ID, P.PRODUCT_NAME, (SUM(O.AMOUNT) * P.PRICE) as TOTAL_SALES
from FOOD_ORDER O
join FOOD_PRODUCT P on P.PRODUCT_ID = O.PRODUCT_ID
where YEAR(O.PRODUCE_DATE) = 2022 and MONTH(O.PRODUCE_DATE) = 5
group by P.PRODUCT_ID, P.PRODUCT_NAME
order by TOTAL_SALES desc, P.PRODUCT_ID asc;