select CATEGORY, sum(BOOK_SALES.SALES) as TOTAL_SALES
from BOOK
inner join BOOK_SALES on BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
where BOOK_SALES.SALES_DATE >= '2022-01-01' and BOOK_SALES.SALES_DATE < '2022-02-01'
group by BOOK.CATEGORY
order by CATEGORY asc