select BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, date_format(BOOK.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK
inner join AUTHOR on BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
where BOOK.CATEGORY = '경제'
order by PUBLISHED_DATE;